 
 const practices = [
    {
         "practiceID": "5",
         "name": "Practice number 1",
         "description": "First Practice of the Year",
         "focus": null,
         "createdate": "2020-12-07",
         "complete": "1",
         "coachID": "5",
         image: require('../assets/golfball.jpg'),
     },
     {
         "practiceID": "6",
         "name": "Practice number 2",
         "description": "Second Practice of the Year",
         "focus": null,
         "createdate": "2020-12-07",
         "complete": "1",
         "coachID": "5",
         image: require('../assets/golfball.jpg'),
     },
     {
         "practiceID": "7",
         "name": "Practice number 3",
         "description": "Third Practice of the Year",
         "focus": null,
         "createdate": "2020-12-07",
         "complete": "1",
         "coachID": "5",
         image: require('../assets/golfball.jpg'),
     },
     {
         "practiceID": "8",
         "name": "Practice number 4",
         "description": "Putting Practice",
         "focus": null,
         "createdate": "2020-12-07",
         "complete": "1",
         "coachID": "5",
         image: require('../assets/golfball.jpg'),
     },
     {
         "practiceID": "9",
         "name": "Putt Better Than The Beginners",
         "description": "First Intermediate Putting Practice",
         "focus": null,
         "createdate": "2020-12-07",
         "complete": "1",
         "coachID": "6",
         image: require('../assets/golfball.jpg'),
     },
     {
         "practiceID": "10",
         "name": "Putt EVEN Better Than The Beginners",
         "description": "Second Intermediate Putting Practice",
         "focus": null,
         "createdate": "2020-12-07",
         "complete": "1",
         "coachID": "6",
         image: require('../assets/golfball.jpg'),
     },
     {
         "practiceID": "11",
         "name": "Putt Better Than The Intermediates",
         "description": "First EXPERT Putting Practice",
         "focus": null,
         "createdate": "2020-12-07",
         "complete": "1",
         "coachID": "7",
         image: require('../assets/golfball.jpg'),
     },
     {
         "practiceID": "12",
         "name": "Putt EVEN Better Than The Intermediates",
         "description": "Second EXPERT Putting Practice",
         "focus": null,
         "createdate": "2020-12-07",
         "complete": "1",
         "coachID": "7",
         image: require('../assets/golfball.jpg'),
     },
     {
         "practiceID": "13",
         "name": "Initial Driving Practice",
         "description": "First Beginner Driving Practice",
         "focus": null,
         "createdate": "2020-12-07",
         "complete": "1",
         "coachID": "8",
         image: require('../assets/golfball.jpg'),
     },
     {
         "practiceID": "14",
         "name": "Get the hang of your driver",
         "description": "Second Beginner Driving Practice",
         "focus": null,
         "createdate": "2020-12-07",
         "complete": "1",
         "coachID": "8",
         image: require('../assets/golfball.jpg'),
     },
     {
         "practiceID": "15",
         "name": "First Intermediate Driving Practice",
         "description": "Intermediate Driving Practice",
         "focus": null,
         "createdate": "2020-12-07",
         "complete": "1",
         "coachID": "9",
         image: require('../assets/golfball.jpg'),
     },
     {
         "practiceID": "16",
         "name": "EXPERT Drills",
         "description": "Normal Expert Practice",
         "focus": null,
         "createdate": "2020-12-07",
         "complete": "1",
         "coachID": "5",
         image: require('../assets/golfball.jpg'),
     },
     {
         "practiceID": "17",
         "name": "Fades ONLY",
         "description": "Expert Drills to hit Fades",
         "focus": null,
         "createdate": "2020-12-07",
         "complete": "1",
         "coachID": "5",
         image: require('../assets/golfball.jpg'),
     },
     {
         "practiceID": "18",
         "name": "Draws ONLY",
         "description": "Expert Drills to hit Draws",
         "focus": null,
         "createdate": "2020-12-07",
         "complete": "1",
         "coachID": "5",
         image: require('../assets/golfball.jpg'),
     },
     {
         "practiceID": "28",
         "name": "New Practice",
         "description": "Try it out",
         "focus": null,
         "createdate": "2020-12-07",
         "complete": "1",
         "coachID": "6",
         image: require('../assets/golfball.jpg'),
     },
     {
         "practiceID": "29",
         "name": "Stack",
         "description": "N Tilt",
         "focus": null,
         "createdate": "2020-12-07",
         "complete": "1",
         "coachID": "6",
         image: require('../assets/golfball.jpg'),
     },
     {
         "practiceID": "31",
         "name": "aefing 1",
         "description": "fyrsta aefing",
         "focus": null,
         "createdate": "2020-12-07",
         "complete": "1",
         "coachID": "5",
         image: require('../assets/golfball.jpg'),
     },
     {
         "practiceID": "33",
         "name": "First Practice to become J Rose",
         "description": "If you wanna learn how to swing it like J Rose join this group",
         "focus": null,
         "createdate": "2020-12-07",
         "complete": "1",
         "coachID": "5",
         image: require('../assets/golfball.jpg'),
     },
     {
         "practiceID": "34",
         "name": "First MasterClass Practice",
         "description": "Test out This new MasterClass Practice",
         "focus": null,
         "createdate": "2020-12-07",
         "complete": "1",
         "coachID": "5",
         image: require('../assets/golfball.jpg'),
     },
     {
         "practiceID": "40",
         "name": "testing",
         "description": "placeholder test",
         "focus": null,
         "createdate": "2020-12-07",
         "complete": "1",
         "coachID": "6",
         image: require('../assets/golfball.jpg'),
     },
     {
         "practiceID": "41",
         "name": "asdf",
         "description": "asdf",
         "focus": null,
         "createdate": "2020-12-07",
         "complete": "1",
         "coachID": "6",
         image: require('../assets/golfball.jpg'),
     },
     {
         "practiceID": "42",
         "name": "f",
         "description": "d",
         "focus": null,
         "createdate": "2020-12-07",
         "complete": "0",
         "coachID": "5",
         image: require('../assets/golfball.jpg'),
     },
     {
         "practiceID": "43",
         "name": "Private Prac",
         "description": "No publics",
         "focus": null,
         "createdate": "2020-12-07",
         "complete": "0",
         "coachID": "6",
         image: require('../assets/golfball.jpg'),
     },
     {
         "practiceID": "44",
         "name": "new driving prac",
         "description": "practice",
         "focus": null,
         "createdate": "2020-12-09",
         "complete": "0",
         "coachID": "5",
         image: require('../assets/golfball.jpg'),
     },
     {
         "practiceID": "45",
         "name": "Overall Short Game Practice",
         "description": "A short game practice that can be done whenever you go golfing. Improve your fundamentals.",
         "focus": null,
         "createdate": "2020-12-11",
         "complete": "1",
         "coachID": "6",
         image: require('../assets/golfball.jpg'),
     },
     {
         "practiceID": "46",
         "name": "ds",
         "description": "fds",
         "focus": null,
         "createdate": "2020-12-13",
         "complete": "1",
         "coachID": "7",
         image: require('../assets/golfball.jpg'),
     },
     {
         "practiceID": "47",
         "name": "asdf",
         "description": "adsf",
         "focus": null,
         "createdate": "2020-12-13",
         "complete": "1",
         "coachID": "7",
         image: require('../assets/golfball.jpg'),
     },
     {
         "practiceID": "48",
         "name": "aefingaefing",
         "description": "practicedescriptionaefing",
         "focus": null,
         "createdate": "2020-12-15",
         "complete": "0",
         "coachID": "7",
         image: require('../assets/golfball.jpg'),
     },
     {
         "practiceID": "49",
         "name": "Simmi",
         "description": "Simmi",
         "focus": null,
         "createdate": "2020-12-16",
         "complete": "1",
         "coachID": "8",
         image: require('../assets/golfball.jpg'),
     }
 ]
 export default practices; 
